//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revelations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.AudioPosts = new HashSet<AudioPost>();
            this.Comments = new HashSet<Comment>();
            this.ImagePosts = new HashSet<ImagePost>();
            this.LinkPosts = new HashSet<LinkPost>();
            this.QuotePosts = new HashSet<QuotePost>();
            this.StandardPosts = new HashSet<StandardPost>();
            this.VideoPosts = new HashSet<VideoPost>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public string Tags { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int AuthorID { get; set; }
        public Nullable<int> LikeCount { get; set; }
    
        public virtual ICollection<AudioPost> AudioPosts { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<ImagePost> ImagePosts { get; set; }
        public virtual ICollection<LinkPost> LinkPosts { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<QuotePost> QuotePosts { get; set; }
        public virtual ICollection<StandardPost> StandardPosts { get; set; }
        public virtual ICollection<VideoPost> VideoPosts { get; set; }
    }
}
