//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revelations.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public User()
        {
            this.Posts = new HashSet<Post>();
        }
    
        public int Id { get; set; }
        [Required (ErrorMessage="Username is required")]
        [StringLength(30,ErrorMessage="First Name is too large")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Password field was not filled")]
        public string Password { get; set; }
        [DataType(DataType.EmailAddress , ErrorMessage = "Email is not valid")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Firstname is required")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Lastname is required")]
        public string LastName { get; set; }
        public string Gender { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
    }
}
